// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: DASH_UI

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_uiRegenPanel = NULL;
lv_obj_t * ui_RegenText = NULL;
lv_obj_t * ui_uiSoCPanel = NULL;
lv_obj_t * ui_BarSoC = NULL;
lv_obj_t * ui_SoCText = NULL;
lv_obj_t * ui_SoCNumerical = NULL;
lv_obj_t * ui_BarTemp = NULL;
lv_obj_t * ui_tempText = NULL;
lv_obj_t * ui_tempNumerical = NULL;
lv_obj_t * ui_hvState = NULL;
lv_obj_t * ui_speedNumerical = NULL;
lv_obj_t * ui_speedText = NULL;
lv_obj_t * ui_tsalText = NULL;
lv_obj_t * ui_BMStateNumerical = NULL;
lv_obj_t * ui_BMSText = NULL;
lv_obj_t * ui_ButtonCoolPump = NULL;
lv_obj_t * ui_CoolPumpText = NULL;
lv_obj_t * ui_ButtonRADFan = NULL;
lv_obj_t * ui_ButtonAccFan = NULL;
lv_obj_t * ui_ButtonRTD = NULL;
lv_obj_t * ui_RadFanText = NULL;
lv_obj_t * ui_AccFanText = NULL;
lv_obj_t * ui_RTDText = NULL;
lv_obj_t * ui_ButtonDataLog = NULL;
lv_obj_t * ui_DataLogText = NULL;
lv_obj_t * ui_ButtonAutoOn = NULL;
lv_obj_t * ui_AutoOnText = NULL;
lv_obj_t * ui_uiAutoMissionPanel = NULL;
lv_obj_t * ui_AutoMissionSelect = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiRegenPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_uiRegenPanel, 794);
    lv_obj_set_height(ui_uiRegenPanel, 50);
    lv_obj_set_x(ui_uiRegenPanel, -1);
    lv_obj_set_y(ui_uiRegenPanel, -212);
    lv_obj_set_align(ui_uiRegenPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiRegenPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RegenText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RegenText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RegenText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RegenText, 9);
    lv_obj_set_y(ui_RegenText, -212);
    lv_obj_set_align(ui_RegenText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RegenText, "REGEN READY");
    lv_obj_set_style_text_font(ui_RegenText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiSoCPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_uiSoCPanel, 792);
    lv_obj_set_height(ui_uiSoCPanel, 105);
    lv_obj_set_x(ui_uiSoCPanel, 0);
    lv_obj_set_y(ui_uiSoCPanel, -129);
    lv_obj_set_align(ui_uiSoCPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiSoCPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarSoC = lv_bar_create(ui_uiSoCPanel);
    lv_bar_set_value(ui_BarSoC, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarSoC, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarSoC, 794);
    lv_obj_set_height(ui_BarSoC, 45);
    lv_obj_set_x(ui_BarSoC, 1);
    lv_obj_set_y(ui_BarSoC, -26);
    lv_obj_set_align(ui_BarSoC, LV_ALIGN_CENTER);

    ui_SoCText = lv_label_create(ui_BarSoC);
    lv_obj_set_width(ui_SoCText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SoCText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SoCText, -29);
    lv_obj_set_y(ui_SoCText, 0);
    lv_obj_set_align(ui_SoCText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SoCText, "SoC:");
    lv_obj_set_style_text_color(ui_SoCText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SoCText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SoCText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoCNumerical = lv_label_create(ui_BarSoC);
    lv_obj_set_width(ui_SoCNumerical, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SoCNumerical, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SoCNumerical, 54);
    lv_obj_set_y(ui_SoCNumerical, 0);
    lv_obj_set_align(ui_SoCNumerical, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SoCNumerical, "XX%");
    lv_obj_set_style_text_color(ui_SoCNumerical, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SoCNumerical, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SoCNumerical, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarTemp = lv_bar_create(ui_uiSoCPanel);
    lv_bar_set_value(ui_BarTemp, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarTemp, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarTemp, 794);
    lv_obj_set_height(ui_BarTemp, 45);
    lv_obj_set_x(ui_BarTemp, 1);
    lv_obj_set_y(ui_BarTemp, 24);
    lv_obj_set_align(ui_BarTemp, LV_ALIGN_CENTER);

    ui_tempText = lv_label_create(ui_BarTemp);
    lv_obj_set_width(ui_tempText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempText, -38);
    lv_obj_set_y(ui_tempText, 3);
    lv_obj_set_align(ui_tempText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempText, "Temp:");
    lv_obj_set_style_text_color(ui_tempText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempNumerical = lv_label_create(ui_uiSoCPanel);
    lv_obj_set_width(ui_tempNumerical, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempNumerical, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempNumerical, 60);
    lv_obj_set_y(ui_tempNumerical, 26);
    lv_obj_set_align(ui_tempNumerical, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempNumerical, "XX°C");
    lv_obj_set_style_text_color(ui_tempNumerical, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempNumerical, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempNumerical, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hvState = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_hvState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hvState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hvState, -239);
    lv_obj_set_y(ui_hvState, -42);
    lv_obj_set_align(ui_hvState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hvState, "HV OFF");
    lv_obj_set_style_text_color(ui_hvState, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hvState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hvState, &ui_font_OrbitronBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedNumerical = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_speedNumerical, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedNumerical, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedNumerical, -7);
    lv_obj_set_y(ui_speedNumerical, -43);
    lv_obj_set_align(ui_speedNumerical, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedNumerical, "XX");
    lv_obj_set_style_text_font(ui_speedNumerical, &ui_font_OrbitronBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_speedText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedText, -7);
    lv_obj_set_y(ui_speedText, -3);
    lv_obj_set_align(ui_speedText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedText, "MPH");
    lv_obj_set_style_text_font(ui_speedText, &ui_font_OrbitronBold15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tsalText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tsalText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tsalText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tsalText, -244);
    lv_obj_set_y(ui_tsalText, -6);
    lv_obj_set_align(ui_tsalText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tsalText, "TSAL");
    lv_obj_set_style_text_font(ui_tsalText, &ui_font_OrbitronBold15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BMStateNumerical = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BMStateNumerical, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BMStateNumerical, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BMStateNumerical, 236);
    lv_obj_set_y(ui_BMStateNumerical, -43);
    lv_obj_set_align(ui_BMStateNumerical, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BMStateNumerical, "NULL");
    lv_obj_set_style_text_font(ui_BMStateNumerical, &ui_font_OrbitronBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BMSText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BMSText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BMSText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BMSText, 233);
    lv_obj_set_y(ui_BMSText, -6);
    lv_obj_set_align(ui_BMSText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BMSText, "BMS");
    lv_obj_set_style_text_font(ui_BMSText, &ui_font_OrbitronBold15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonCoolPump = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonCoolPump, 120);
    lv_obj_set_height(ui_ButtonCoolPump, 65);
    lv_obj_set_x(ui_ButtonCoolPump, -263);
    lv_obj_set_y(ui_ButtonCoolPump, 61);
    lv_obj_set_align(ui_ButtonCoolPump, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCoolPump, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCoolPump, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonCoolPump, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCoolPump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CoolPumpText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CoolPumpText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CoolPumpText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CoolPumpText, -263);
    lv_obj_set_y(ui_CoolPumpText, 63);
    lv_obj_set_align(ui_CoolPumpText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CoolPumpText, "Cool\nPump");
    lv_obj_set_style_text_font(ui_CoolPumpText, &ui_font_OrbitronBold25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRADFan = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonRADFan, 120);
    lv_obj_set_height(ui_ButtonRADFan, 65);
    lv_obj_set_x(ui_ButtonRADFan, -102);
    lv_obj_set_y(ui_ButtonRADFan, 62);
    lv_obj_set_align(ui_ButtonRADFan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRADFan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRADFan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRADFan, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRADFan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonAccFan = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonAccFan, 120);
    lv_obj_set_height(ui_ButtonAccFan, 65);
    lv_obj_set_x(ui_ButtonAccFan, 61);
    lv_obj_set_y(ui_ButtonAccFan, 62);
    lv_obj_set_align(ui_ButtonAccFan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonAccFan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonAccFan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonAccFan, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonAccFan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRTD = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonRTD, 120);
    lv_obj_set_height(ui_ButtonRTD, 65);
    lv_obj_set_x(ui_ButtonRTD, 240);
    lv_obj_set_y(ui_ButtonRTD, 63);
    lv_obj_set_align(ui_ButtonRTD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRTD, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRTD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRTD, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRTD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RadFanText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RadFanText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RadFanText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RadFanText, -101);
    lv_obj_set_y(ui_RadFanText, 63);
    lv_obj_set_align(ui_RadFanText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RadFanText, "RAD\nFAN");
    lv_obj_set_style_text_font(ui_RadFanText, &ui_font_OrbitronBold25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccFanText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AccFanText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccFanText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccFanText, 60);
    lv_obj_set_y(ui_AccFanText, 65);
    lv_obj_set_align(ui_AccFanText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccFanText, "ACC\nFAN");
    lv_obj_set_style_text_font(ui_AccFanText, &ui_font_OrbitronBold25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RTDText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RTDText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RTDText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RTDText, 238);
    lv_obj_set_y(ui_RTDText, 63);
    lv_obj_set_align(ui_RTDText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RTDText, "RTD");
    lv_obj_set_style_text_font(ui_RTDText, &ui_font_OrbitronBold25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonDataLog = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonDataLog, 120);
    lv_obj_set_height(ui_ButtonDataLog, 65);
    lv_obj_set_x(ui_ButtonDataLog, 62);
    lv_obj_set_y(ui_ButtonDataLog, 141);
    lv_obj_set_align(ui_ButtonDataLog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonDataLog, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonDataLog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonDataLog, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonDataLog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DataLogText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_DataLogText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DataLogText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DataLogText, 60);
    lv_obj_set_y(ui_DataLogText, 142);
    lv_obj_set_align(ui_DataLogText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DataLogText, "DATA\nLOG");
    lv_obj_set_style_text_font(ui_DataLogText, &ui_font_OrbitronBold25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonAutoOn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonAutoOn, 120);
    lv_obj_set_height(ui_ButtonAutoOn, 65);
    lv_obj_set_x(ui_ButtonAutoOn, -101);
    lv_obj_set_y(ui_ButtonAutoOn, 142);
    lv_obj_set_align(ui_ButtonAutoOn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonAutoOn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonAutoOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonAutoOn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonAutoOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AutoOnText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AutoOnText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AutoOnText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AutoOnText, -99);
    lv_obj_set_y(ui_AutoOnText, 142);
    lv_obj_set_align(ui_AutoOnText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AutoOnText, "AUTO\nON");
    lv_obj_set_style_text_font(ui_AutoOnText, &ui_font_OrbitronBold25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiAutoMissionPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_uiAutoMissionPanel, 741);
    lv_obj_set_height(ui_uiAutoMissionPanel, 45);
    lv_obj_set_x(ui_uiAutoMissionPanel, 1);
    lv_obj_set_y(ui_uiAutoMissionPanel, 203);
    lv_obj_set_align(ui_uiAutoMissionPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiAutoMissionPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AutoMissionSelect = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AutoMissionSelect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AutoMissionSelect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AutoMissionSelect, -5);
    lv_obj_set_y(ui_AutoMissionSelect, 205);
    lv_obj_set_align(ui_AutoMissionSelect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AutoMissionSelect, "AUTO MISSION: NULL");
    lv_obj_set_style_text_font(ui_AutoMissionSelect, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_uiRegenPanel = NULL;
    ui_RegenText = NULL;
    ui_uiSoCPanel = NULL;
    ui_BarSoC = NULL;
    ui_SoCText = NULL;
    ui_SoCNumerical = NULL;
    ui_BarTemp = NULL;
    ui_tempText = NULL;
    ui_tempNumerical = NULL;
    ui_hvState = NULL;
    ui_speedNumerical = NULL;
    ui_speedText = NULL;
    ui_tsalText = NULL;
    ui_BMStateNumerical = NULL;
    ui_BMSText = NULL;
    ui_ButtonCoolPump = NULL;
    ui_CoolPumpText = NULL;
    ui_ButtonRADFan = NULL;
    ui_ButtonAccFan = NULL;
    ui_ButtonRTD = NULL;
    ui_RadFanText = NULL;
    ui_AccFanText = NULL;
    ui_RTDText = NULL;
    ui_ButtonDataLog = NULL;
    ui_DataLogText = NULL;
    ui_ButtonAutoOn = NULL;
    ui_AutoOnText = NULL;
    ui_uiAutoMissionPanel = NULL;
    ui_AutoMissionSelect = NULL;

}
