// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: DASH_UI

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_uiRegenPanel;
extern lv_obj_t * ui_RegenText;
extern lv_obj_t * ui_uiSoCPanel;
extern lv_obj_t * ui_BarSoC;
extern lv_obj_t * ui_SoCText;
extern lv_obj_t * ui_SoCNumerical;
extern lv_obj_t * ui_BarTemp;
extern lv_obj_t * ui_tempText;
extern lv_obj_t * ui_tempNumerical;
extern lv_obj_t * ui_hvState;
extern lv_obj_t * ui_speedNumerical;
extern lv_obj_t * ui_speedText;
extern lv_obj_t * ui_tsalText;
extern lv_obj_t * ui_BMStateNumerical;
extern lv_obj_t * ui_BMSText;
extern lv_obj_t * ui_ButtonCoolPump;
extern lv_obj_t * ui_CoolPumpText;
extern lv_obj_t * ui_ButtonRADFan;
extern lv_obj_t * ui_ButtonAccFan;
extern lv_obj_t * ui_ButtonRTD;
extern lv_obj_t * ui_RadFanText;
extern lv_obj_t * ui_AccFanText;
extern lv_obj_t * ui_RTDText;
extern lv_obj_t * ui_ButtonDataLog;
extern lv_obj_t * ui_DataLogText;
extern lv_obj_t * ui_ButtonAutoOn;
extern lv_obj_t * ui_AutoOnText;
extern lv_obj_t * ui_uiAutoMissionPanel;
extern lv_obj_t * ui_AutoMissionSelect;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

