/**
 * @file feb_can.h
 *
 * @brief This header file was generated by cantools version 40.2.1 Sun Mar  9 15:26:07 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef FEB_CAN_H
#define FEB_CAN_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define FEB_CAN_FEB_BMS_CELL_VOLTAGE_FRAME_ID (0x00u)
#define FEB_CAN_FEB_IV_METER_FRAME_ID (0x01u)
#define FEB_CAN_FEB_LVPDB_FLAGS_BUS_VOLTAGE_FRAME_ID (0x02u)
#define FEB_CAN_FEB_LVPDB_LV_CP_CURRENT_FRAME_ID (0x03u)
#define FEB_CAN_FEB_LVPDB_AF_RF_CURRENT_FRAME_ID (0x04u)
#define FEB_CAN_FEB_LVPDB_SH_L_CURRENT_FRAME_ID (0x05u)
#define FEB_CAN_FEB_LVPDB_AS_AB_CURRENT_FRAME_ID (0x06u)
#define FEB_CAN_FEB_DASH_MESSAGE_FRAME_ID (0x07u)
#define FEB_CAN_FEB_DART_TACH_MEASUREMENTS_FRAME_ID (0x08u)
#define FEB_CAN_FEB_PING_PONG_COUNTER1_FRAME_ID (0x09u)
#define FEB_CAN_FEB_PING_PONG_COUNTER2_FRAME_ID (0x0au)
#define FEB_CAN_FEB_PING_PONG_COUNTER3_FRAME_ID (0x0bu)
#define FEB_CAN_FEB_PING_PONG_COUNTER4_FRAME_ID (0x0cu)

/* Frame lengths in bytes. */
#define FEB_CAN_FEB_BMS_CELL_VOLTAGE_LENGTH (4u)
#define FEB_CAN_FEB_IV_METER_LENGTH (4u)
#define FEB_CAN_FEB_LVPDB_FLAGS_BUS_VOLTAGE_LENGTH (8u)
#define FEB_CAN_FEB_LVPDB_LV_CP_CURRENT_LENGTH (8u)
#define FEB_CAN_FEB_LVPDB_AF_RF_CURRENT_LENGTH (8u)
#define FEB_CAN_FEB_LVPDB_SH_L_CURRENT_LENGTH (8u)
#define FEB_CAN_FEB_LVPDB_AS_AB_CURRENT_LENGTH (8u)
#define FEB_CAN_FEB_DASH_MESSAGE_LENGTH (1u)
#define FEB_CAN_FEB_DART_TACH_MEASUREMENTS_LENGTH (5u)
#define FEB_CAN_FEB_PING_PONG_COUNTER1_LENGTH (8u)
#define FEB_CAN_FEB_PING_PONG_COUNTER2_LENGTH (8u)
#define FEB_CAN_FEB_PING_PONG_COUNTER3_LENGTH (8u)
#define FEB_CAN_FEB_PING_PONG_COUNTER4_LENGTH (8u)

/* Extended or standard frame types. */
#define FEB_CAN_FEB_BMS_CELL_VOLTAGE_IS_EXTENDED (0)
#define FEB_CAN_FEB_IV_METER_IS_EXTENDED (0)
#define FEB_CAN_FEB_LVPDB_FLAGS_BUS_VOLTAGE_IS_EXTENDED (0)
#define FEB_CAN_FEB_LVPDB_LV_CP_CURRENT_IS_EXTENDED (0)
#define FEB_CAN_FEB_LVPDB_AF_RF_CURRENT_IS_EXTENDED (0)
#define FEB_CAN_FEB_LVPDB_SH_L_CURRENT_IS_EXTENDED (0)
#define FEB_CAN_FEB_LVPDB_AS_AB_CURRENT_IS_EXTENDED (0)
#define FEB_CAN_FEB_DASH_MESSAGE_IS_EXTENDED (0)
#define FEB_CAN_FEB_DART_TACH_MEASUREMENTS_IS_EXTENDED (0)
#define FEB_CAN_FEB_PING_PONG_COUNTER1_IS_EXTENDED (0)
#define FEB_CAN_FEB_PING_PONG_COUNTER2_IS_EXTENDED (0)
#define FEB_CAN_FEB_PING_PONG_COUNTER3_IS_EXTENDED (0)
#define FEB_CAN_FEB_PING_PONG_COUNTER4_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define FEB_CAN_FEB_BMS_CELL_VOLTAGE_NAME "FEB_BMS_Cell_Voltage"
#define FEB_CAN_FEB_IV_METER_NAME "FEB_IVMeter"
#define FEB_CAN_FEB_LVPDB_FLAGS_BUS_VOLTAGE_NAME "FEB_LVPDB_Flags_Bus_Voltage"
#define FEB_CAN_FEB_LVPDB_LV_CP_CURRENT_NAME "FEB_LVPDB_LV_CP_Current"
#define FEB_CAN_FEB_LVPDB_AF_RF_CURRENT_NAME "FEB_LVPDB_AF_RF_Current"
#define FEB_CAN_FEB_LVPDB_SH_L_CURRENT_NAME "FEB_LVPDB_SH_L_Current"
#define FEB_CAN_FEB_LVPDB_AS_AB_CURRENT_NAME "FEB_LVPDB_AS_AB_Current"
#define FEB_CAN_FEB_DASH_MESSAGE_NAME "FEB_Dash_Message"
#define FEB_CAN_FEB_DART_TACH_MEASUREMENTS_NAME "FEB_DART_TACH_measurements"
#define FEB_CAN_FEB_PING_PONG_COUNTER1_NAME "FEB_PING_PONG_counter1"
#define FEB_CAN_FEB_PING_PONG_COUNTER2_NAME "FEB_PING_PONG_counter2"
#define FEB_CAN_FEB_PING_PONG_COUNTER3_NAME "FEB_PING_PONG_counter3"
#define FEB_CAN_FEB_PING_PONG_COUNTER4_NAME "FEB_PING_PONG_counter4"

/* Signal Names. */
#define FEB_CAN_FEB_BMS_CELL_VOLTAGE_BANK_NUMBER_NAME "bank_number"
#define FEB_CAN_FEB_BMS_CELL_VOLTAGE_CELL_NUMBER_NAME "cell_number"
#define FEB_CAN_FEB_BMS_CELL_VOLTAGE_CELL_VOLTAGE_NAME "cell_voltage"
#define FEB_CAN_FEB_IV_METER_LOW_RANGE_CURRENT_NAME "low_range_current"
#define FEB_CAN_FEB_IV_METER_HIGH_RANGE_CURRENT_NAME "high_range_current"
#define FEB_CAN_FEB_IV_METER_HV_VOLTAGE_NAME "hv_voltage"
#define FEB_CAN_FEB_LVPDB_FLAGS_BUS_VOLTAGE_FLAGS_NAME "flags"
#define FEB_CAN_FEB_LVPDB_FLAGS_BUS_VOLTAGE_BUS_VOLTAGE_NAME "bus_voltage"
#define FEB_CAN_FEB_LVPDB_LV_CP_CURRENT_LV_CURRENT_NAME "lv_current"
#define FEB_CAN_FEB_LVPDB_LV_CP_CURRENT_CP_VOLTAGE_NAME "cp_voltage"
#define FEB_CAN_FEB_LVPDB_AF_RF_CURRENT_AF_CURRENT_NAME "af_current"
#define FEB_CAN_FEB_LVPDB_AF_RF_CURRENT_RF_VOLTAGE_NAME "rf_voltage"
#define FEB_CAN_FEB_LVPDB_SH_L_CURRENT_SH_CURRENT_NAME "sh_current"
#define FEB_CAN_FEB_LVPDB_SH_L_CURRENT_L_VOLTAGE_NAME "l_voltage"
#define FEB_CAN_FEB_LVPDB_AS_AB_CURRENT_LV_CURRENT_NAME "lv_current"
#define FEB_CAN_FEB_LVPDB_AS_AB_CURRENT_CP_VOLTAGE_NAME "cp_voltage"
#define FEB_CAN_FEB_DASH_MESSAGE_BUZZER_STATE_NAME "buzzer_state"
#define FEB_CAN_FEB_DASH_MESSAGE_BUTTON1_READY_TO_DRIVE_NAME "button1_ready_to_drive"
#define FEB_CAN_FEB_DASH_MESSAGE_BUTTON2_NAME "button2"
#define FEB_CAN_FEB_DASH_MESSAGE_BUTTON3_NAME "button3"
#define FEB_CAN_FEB_DASH_MESSAGE_BUTTON4_NAME "button4"
#define FEB_CAN_FEB_DASH_MESSAGE_COOLANT_PUMP_SWITCH_NAME "coolant_pump_switch"
#define FEB_CAN_FEB_DASH_MESSAGE_RADIATOR_FAN_SWITCH_NAME "radiator_fan_switch"
#define FEB_CAN_FEB_DASH_MESSAGE_ACCUMULATOR_FAN_SWITCH_NAME "accumulator_fan_switch"
#define FEB_CAN_FEB_DART_TACH_MEASUREMENTS_FAN1_SPEED_NAME "fan1_speed"
#define FEB_CAN_FEB_DART_TACH_MEASUREMENTS_FAN2_SPEED_NAME "fan2_speed"
#define FEB_CAN_FEB_DART_TACH_MEASUREMENTS_FAN3_SPEED_NAME "fan3_speed"
#define FEB_CAN_FEB_DART_TACH_MEASUREMENTS_FAN4_SPEED_NAME "fan4_speed"
#define FEB_CAN_FEB_DART_TACH_MEASUREMENTS_FAN5_SPEED_NAME "fan5_speed"
#define FEB_CAN_FEB_PING_PONG_COUNTER1_COUNTER_NAME "counter"
#define FEB_CAN_FEB_PING_PONG_COUNTER2_COUNTER_NAME "counter"
#define FEB_CAN_FEB_PING_PONG_COUNTER3_COUNTER_NAME "counter"
#define FEB_CAN_FEB_PING_PONG_COUNTER4_COUNTER_NAME "counter"

/**
 * Signals in message FEB_BMS_Cell_Voltage.
 *
 * BMS message for cell voltage.
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_feb_bms_cell_voltage_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t bank_number;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t cell_number;

    /**
     * Range: -
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t cell_voltage;
};

/**
 * Signals in message FEB_IVMeter.
 *
 * ivMeter message for low and high range current and HV voltage.
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_feb_iv_meter_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t low_range_current;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t high_range_current;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t hv_voltage;
};

/**
 * Signals in message FEB_LVPDB_Flags_Bus_Voltage.
 *
 * LVPDB message for flags and bus voltage.
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_feb_lvpdb_flags_bus_voltage_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t flags;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float bus_voltage;
};

/**
 * Signals in message FEB_LVPDB_LV_CP_Current.
 *
 * LVPDB message for Low Voltage and Coolant Pump Current.
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_feb_lvpdb_lv_cp_current_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float lv_current;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float cp_voltage;
};

/**
 * Signals in message FEB_LVPDB_AF_RF_Current.
 *
 * LVPDB message for Rad Fans and Acc Fans Current.
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_feb_lvpdb_af_rf_current_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float af_current;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float rf_voltage;
};

/**
 * Signals in message FEB_LVPDB_SH_L_Current.
 *
 * LVPDB message for Shutdown and Lidar Current.
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_feb_lvpdb_sh_l_current_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float sh_current;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float l_voltage;
};

/**
 * Signals in message FEB_LVPDB_AS_AB_Current.
 *
 * LVPDB message for Auton Steering and Auton Braking Current.
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_feb_lvpdb_as_ab_current_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float lv_current;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float cp_voltage;
};

/**
 * Signals in message FEB_Dash_Message.
 *
 * Dash message
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_feb_dash_message_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t buzzer_state;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t button1_ready_to_drive;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t button2;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t button3;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t button4;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t coolant_pump_switch;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t radiator_fan_switch;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t accumulator_fan_switch;
};

/**
 * Signals in message FEB_DART_TACH_measurements.
 *
 * DART message for Tachometer measurements.
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_feb_dart_tach_measurements_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t fan1_speed;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t fan2_speed;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t fan3_speed;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t fan4_speed;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t fan5_speed;
};

/**
 * Signals in message FEB_PING_PONG_counter1.
 *
 * PING PONG counter1.
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_feb_ping_pong_counter1_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t counter;
};

/**
 * Signals in message FEB_PING_PONG_counter2.
 *
 * PING PONG counter2.
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_feb_ping_pong_counter2_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t counter;
};

/**
 * Signals in message FEB_PING_PONG_counter3.
 *
 * PING PONG counter3.
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_feb_ping_pong_counter3_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t counter;
};

/**
 * Signals in message FEB_PING_PONG_counter4.
 *
 * PING PONG counter4.
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_feb_ping_pong_counter4_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t counter;
};

/**
 * Pack message FEB_BMS_Cell_Voltage.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_feb_bms_cell_voltage_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_bms_cell_voltage_t *src_p,
    size_t size);

/**
 * Unpack message FEB_BMS_Cell_Voltage.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_feb_bms_cell_voltage_unpack(
    struct feb_can_feb_bms_cell_voltage_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEB_BMS_Cell_Voltage.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_feb_bms_cell_voltage_init(struct feb_can_feb_bms_cell_voltage_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_bms_cell_voltage_bank_number_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_bms_cell_voltage_bank_number_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_bms_cell_voltage_bank_number_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_bms_cell_voltage_cell_number_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_bms_cell_voltage_cell_number_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_bms_cell_voltage_cell_number_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t feb_can_feb_bms_cell_voltage_cell_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_bms_cell_voltage_cell_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_bms_cell_voltage_cell_voltage_is_in_range(uint16_t value);

/**
 * Pack message FEB_IVMeter.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_feb_iv_meter_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_iv_meter_t *src_p,
    size_t size);

/**
 * Unpack message FEB_IVMeter.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_feb_iv_meter_unpack(
    struct feb_can_feb_iv_meter_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEB_IVMeter.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_feb_iv_meter_init(struct feb_can_feb_iv_meter_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_iv_meter_low_range_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_iv_meter_low_range_current_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_iv_meter_low_range_current_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_iv_meter_high_range_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_iv_meter_high_range_current_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_iv_meter_high_range_current_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_iv_meter_hv_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_iv_meter_hv_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_iv_meter_hv_voltage_is_in_range(uint8_t value);

/**
 * Pack message FEB_LVPDB_Flags_Bus_Voltage.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_feb_lvpdb_flags_bus_voltage_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_lvpdb_flags_bus_voltage_t *src_p,
    size_t size);

/**
 * Unpack message FEB_LVPDB_Flags_Bus_Voltage.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_feb_lvpdb_flags_bus_voltage_unpack(
    struct feb_can_feb_lvpdb_flags_bus_voltage_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEB_LVPDB_Flags_Bus_Voltage.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_feb_lvpdb_flags_bus_voltage_init(struct feb_can_feb_lvpdb_flags_bus_voltage_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t feb_can_feb_lvpdb_flags_bus_voltage_flags_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_lvpdb_flags_bus_voltage_flags_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_lvpdb_flags_bus_voltage_flags_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float feb_can_feb_lvpdb_flags_bus_voltage_bus_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_lvpdb_flags_bus_voltage_bus_voltage_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_lvpdb_flags_bus_voltage_bus_voltage_is_in_range(float value);

/**
 * Pack message FEB_LVPDB_LV_CP_Current.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_feb_lvpdb_lv_cp_current_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_lvpdb_lv_cp_current_t *src_p,
    size_t size);

/**
 * Unpack message FEB_LVPDB_LV_CP_Current.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_feb_lvpdb_lv_cp_current_unpack(
    struct feb_can_feb_lvpdb_lv_cp_current_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEB_LVPDB_LV_CP_Current.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_feb_lvpdb_lv_cp_current_init(struct feb_can_feb_lvpdb_lv_cp_current_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float feb_can_feb_lvpdb_lv_cp_current_lv_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_lvpdb_lv_cp_current_lv_current_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_lvpdb_lv_cp_current_lv_current_is_in_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float feb_can_feb_lvpdb_lv_cp_current_cp_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_lvpdb_lv_cp_current_cp_voltage_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_lvpdb_lv_cp_current_cp_voltage_is_in_range(float value);

/**
 * Pack message FEB_LVPDB_AF_RF_Current.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_feb_lvpdb_af_rf_current_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_lvpdb_af_rf_current_t *src_p,
    size_t size);

/**
 * Unpack message FEB_LVPDB_AF_RF_Current.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_feb_lvpdb_af_rf_current_unpack(
    struct feb_can_feb_lvpdb_af_rf_current_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEB_LVPDB_AF_RF_Current.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_feb_lvpdb_af_rf_current_init(struct feb_can_feb_lvpdb_af_rf_current_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float feb_can_feb_lvpdb_af_rf_current_af_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_lvpdb_af_rf_current_af_current_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_lvpdb_af_rf_current_af_current_is_in_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float feb_can_feb_lvpdb_af_rf_current_rf_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_lvpdb_af_rf_current_rf_voltage_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_lvpdb_af_rf_current_rf_voltage_is_in_range(float value);

/**
 * Pack message FEB_LVPDB_SH_L_Current.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_feb_lvpdb_sh_l_current_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_lvpdb_sh_l_current_t *src_p,
    size_t size);

/**
 * Unpack message FEB_LVPDB_SH_L_Current.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_feb_lvpdb_sh_l_current_unpack(
    struct feb_can_feb_lvpdb_sh_l_current_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEB_LVPDB_SH_L_Current.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_feb_lvpdb_sh_l_current_init(struct feb_can_feb_lvpdb_sh_l_current_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float feb_can_feb_lvpdb_sh_l_current_sh_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_lvpdb_sh_l_current_sh_current_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_lvpdb_sh_l_current_sh_current_is_in_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float feb_can_feb_lvpdb_sh_l_current_l_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_lvpdb_sh_l_current_l_voltage_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_lvpdb_sh_l_current_l_voltage_is_in_range(float value);

/**
 * Pack message FEB_LVPDB_AS_AB_Current.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_feb_lvpdb_as_ab_current_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_lvpdb_as_ab_current_t *src_p,
    size_t size);

/**
 * Unpack message FEB_LVPDB_AS_AB_Current.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_feb_lvpdb_as_ab_current_unpack(
    struct feb_can_feb_lvpdb_as_ab_current_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEB_LVPDB_AS_AB_Current.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_feb_lvpdb_as_ab_current_init(struct feb_can_feb_lvpdb_as_ab_current_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float feb_can_feb_lvpdb_as_ab_current_lv_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_lvpdb_as_ab_current_lv_current_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_lvpdb_as_ab_current_lv_current_is_in_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float feb_can_feb_lvpdb_as_ab_current_cp_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_lvpdb_as_ab_current_cp_voltage_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_lvpdb_as_ab_current_cp_voltage_is_in_range(float value);

/**
 * Pack message FEB_Dash_Message.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_feb_dash_message_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_dash_message_t *src_p,
    size_t size);

/**
 * Unpack message FEB_Dash_Message.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_feb_dash_message_unpack(
    struct feb_can_feb_dash_message_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEB_Dash_Message.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_feb_dash_message_init(struct feb_can_feb_dash_message_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_dash_message_buzzer_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_dash_message_buzzer_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_dash_message_buzzer_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_dash_message_button1_ready_to_drive_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_dash_message_button1_ready_to_drive_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_dash_message_button1_ready_to_drive_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_dash_message_button2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_dash_message_button2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_dash_message_button2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_dash_message_button3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_dash_message_button3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_dash_message_button3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_dash_message_button4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_dash_message_button4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_dash_message_button4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_dash_message_coolant_pump_switch_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_dash_message_coolant_pump_switch_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_dash_message_coolant_pump_switch_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_dash_message_radiator_fan_switch_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_dash_message_radiator_fan_switch_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_dash_message_radiator_fan_switch_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_dash_message_accumulator_fan_switch_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_dash_message_accumulator_fan_switch_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_dash_message_accumulator_fan_switch_is_in_range(uint8_t value);

/**
 * Pack message FEB_DART_TACH_measurements.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_feb_dart_tach_measurements_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_dart_tach_measurements_t *src_p,
    size_t size);

/**
 * Unpack message FEB_DART_TACH_measurements.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_feb_dart_tach_measurements_unpack(
    struct feb_can_feb_dart_tach_measurements_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEB_DART_TACH_measurements.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_feb_dart_tach_measurements_init(struct feb_can_feb_dart_tach_measurements_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_dart_tach_measurements_fan1_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_dart_tach_measurements_fan1_speed_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_dart_tach_measurements_fan1_speed_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_dart_tach_measurements_fan2_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_dart_tach_measurements_fan2_speed_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_dart_tach_measurements_fan2_speed_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_dart_tach_measurements_fan3_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_dart_tach_measurements_fan3_speed_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_dart_tach_measurements_fan3_speed_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_dart_tach_measurements_fan4_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_dart_tach_measurements_fan4_speed_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_dart_tach_measurements_fan4_speed_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t feb_can_feb_dart_tach_measurements_fan5_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_dart_tach_measurements_fan5_speed_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_dart_tach_measurements_fan5_speed_is_in_range(uint8_t value);

/**
 * Pack message FEB_PING_PONG_counter1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_feb_ping_pong_counter1_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_ping_pong_counter1_t *src_p,
    size_t size);

/**
 * Unpack message FEB_PING_PONG_counter1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_feb_ping_pong_counter1_unpack(
    struct feb_can_feb_ping_pong_counter1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEB_PING_PONG_counter1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_feb_ping_pong_counter1_init(struct feb_can_feb_ping_pong_counter1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t feb_can_feb_ping_pong_counter1_counter_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_ping_pong_counter1_counter_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_ping_pong_counter1_counter_is_in_range(int32_t value);

/**
 * Pack message FEB_PING_PONG_counter2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_feb_ping_pong_counter2_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_ping_pong_counter2_t *src_p,
    size_t size);

/**
 * Unpack message FEB_PING_PONG_counter2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_feb_ping_pong_counter2_unpack(
    struct feb_can_feb_ping_pong_counter2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEB_PING_PONG_counter2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_feb_ping_pong_counter2_init(struct feb_can_feb_ping_pong_counter2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t feb_can_feb_ping_pong_counter2_counter_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_ping_pong_counter2_counter_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_ping_pong_counter2_counter_is_in_range(int32_t value);

/**
 * Pack message FEB_PING_PONG_counter3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_feb_ping_pong_counter3_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_ping_pong_counter3_t *src_p,
    size_t size);

/**
 * Unpack message FEB_PING_PONG_counter3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_feb_ping_pong_counter3_unpack(
    struct feb_can_feb_ping_pong_counter3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEB_PING_PONG_counter3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_feb_ping_pong_counter3_init(struct feb_can_feb_ping_pong_counter3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t feb_can_feb_ping_pong_counter3_counter_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_ping_pong_counter3_counter_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_ping_pong_counter3_counter_is_in_range(int32_t value);

/**
 * Pack message FEB_PING_PONG_counter4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_feb_ping_pong_counter4_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_ping_pong_counter4_t *src_p,
    size_t size);

/**
 * Unpack message FEB_PING_PONG_counter4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_feb_ping_pong_counter4_unpack(
    struct feb_can_feb_ping_pong_counter4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEB_PING_PONG_counter4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_feb_ping_pong_counter4_init(struct feb_can_feb_ping_pong_counter4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t feb_can_feb_ping_pong_counter4_counter_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_feb_ping_pong_counter4_counter_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_feb_ping_pong_counter4_counter_is_in_range(int32_t value);


#ifdef __cplusplus
}
#endif

#endif
