// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: ics_test

#ifndef _ICS_TEST_UI_H
#define _ICS_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_Bar2;
extern lv_obj_t *ui_Bar3;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_TextArea2;
extern lv_obj_t *ui_TextArea4;
extern lv_obj_t *ui_TextArea3;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui____initial_actions0;
extern lv_obj_t * img_regen_status;
extern lv_obj_t * img_ones_place;
extern lv_obj_t * img_tens_place;
extern lv_obj_t * img_v;
extern lv_obj_t * img_ones_place1;
extern lv_obj_t * img_tens_place1;
extern lv_obj_t * img_degrees;
extern lv_obj_t * img_ones_place2;
extern lv_obj_t * img_tens_place2;
extern lv_obj_t * img_tsal_status;
extern lv_obj_t * img_bms_status;
extern lv_obj_t * img_decimal;

LV_FONT_DECLARE( ui_font_intervar52);
LV_FONT_DECLARE( ui_font_robotf);
LV_FONT_DECLARE( ui_font_roboto20);
LV_FONT_DECLARE( ui_font_roboto42);
LV_FONT_DECLARE( ui_font_roboto52);
LV_FONT_DECLARE( ui_font_roboto60);

void ui_init(void);
void set_soc_value(uint16_t value);
void set_temp_value(uint8_t value);
void set_speed_value(uint16_t value);
void set_tsal_status(uint8_t value);
void set_bms_status(uint8_t value);
void set_regen_status(uint8_t value);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
